on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          python-version: 3.9.7

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas

      - name: Install yahoo finance
        run: python -m pip install yfinance

      - name: Run Python script
        run: python 2023_06_14__stock_predict.py
